### ISSUE TITLE
Add {{TOC}} support

### ISSUE THREAD

**Issue by Yaty** [jstransformers/jstransformer-mmd#7]
My bad, I'll see with https://github.com/mnichols/node-mmd
~~Hi,
I think it could be great to add {{TOC}} (table of contents) generation.
http://fletcherpenney.net/multimarkdown/ is using it.~~

**Comment by RobLoach** [comment]
How did you do it?

**Comment by Yaty** [comment]
For now I'm using node child_process.exec() with [multimarkdown](http://fletcherpenney.net/multimarkdown/).
